### ISSUE TITLE
Clicking on settings does not open settings 

### ISSUE THREAD

**Issue by umair1209** [dtube/embed#12]
#### Expected behavior
Clicking on settings should open the settings and we should be able to change them as desired. 

#### Actual behavior
I clicked on settings multiple times but somehow settings did not open. 

#### How to reproduce

- Open dtube 
- Select a video and open it
- Click on settings, it wont open settings 

* Browser: Google chrome for Android latest version. 
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/g6zUFBM-0kA    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/clicking-on-settings-does-not-open-settings">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by skzap** [comment]
I see this bug. On Safari the same behavior almost, except if you hold the tap for a bit (half a sec), it opens the menu. Is it the same on android?

**Comment by skzap** [comment]
This is linked to our recent player update and should be resolved asap

**Comment by umair1209** [comment]
I was able to access settings when I clicked and held for half a second as you mentioned.

On 28 Feb 2018 10:36 p.m., heimindanger <notifications@github.com> wrote:

I see this bug. On Safari the same behavior almost, except if you hold the tap for a bit (half a sec), it opens the menu. Is it the same on android?

**Comment by powerpoint45** [comment]
Running Android 8.1.0 I can open settings if I press for about a second as @skzap mentioned. Other android versions may not work though. Can't check right now.
