### ISSUE TITLE
Embed DTube Video into your website

### ISSUE THREAD

**Issue by SophieElle** [dtube/embed#36]
Hello,
can't get a DTube video to work on my website: copied the iframe-code above and pasted my DTube URL: nothing.

Also downloaded emde master: nothing

Who can help a layman?
By the way: even the Chrome extension does not work for me: nothing is displayed

**Comment by maledorak** [comment]
@SophieElle You need to provide more information about your problem, e.g. some sreenshots from chrome dev tools console.

Btw: lately I created embed code generator for DTube: 
https://embed.tube/embed-code-generator/dtube/
It will create responsive html code for you.

**Comment by skzap** [comment]
@maledorak thats pretty cool tool !

We already have a button to generate an embed code, also though it's very simple and just copies it into clipboard:
![https://i.imgur.com/ddHshN3.png](https://i.imgur.com/ddHshN3.png)

It was re-added recently, I believe it wasn't there when the user created the issue

**Comment by maledorak** [comment]
> @maledorak thats pretty cool tool !
Thanks I appreciate it :)
I released it in last week, so no one knows about it for now :P

**Comment by maledorak** [comment]
@skzap 
Thanks, I appreciate it :)
I released in in last week though no one knows about it for now :P
