### ISSUE TITLE
No way to disable autoplay for youtube redirect embedded videos

### ISSUE THREAD

**Issue by Novusphere** [dtube/embed#37]
Example: https://emb.d.tube/#!/thecastle/2pt3qr2czbl redirects to https://www.youtube.com/embed/zJyTPCNpCGg?autoplay=1&showinfo=1&modestbranding=1

There's no clear way in how to disable the autoplay flag from being set. The obvious work around is to make my users have to click something before the iframe/embed is even loaded but it would be nice if the dtube embed url provided an option for this or **by default didn't autoplay like most video players...**

The API specifies: `The syntax is as follow /#!/author/permlink/autoplay/branding`

However: https://emb.d.tube/#!/thecastle/2pt3qr2czbl/false or https://emb.d.tube/#!/thecastle/2pt3qr2czbl/0 still autoplays with a redirect to https://www.youtube.com/embed/zJyTPCNpCGg?autoplay=1&showinfo=1&modestbranding=1

**Comment by skzap** [comment]
Right, this is a mistake in the player code, the autoplay only applies to IPFS/BTFS/Skynet videos, not the 3rd party embeds. I will get it fixed asap

**Comment by skzap** [comment]
@Novusphere Okay I believe it should be working as expected now after this fix that just went live: https://github.com/dtube/embed/commit/45e737a886fe56eac74b526adb6d43a8709d5af7

Also please keep in mind that the autoplay option is not available for all 3rd parties... only YT, Twitch, Dailymotion, Vimeo and Facebook.
