### ISSUE TITLE
HLS and DASH Support

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/embed#47]
It would be incredible for extreme quality videos if we could allow for HLS and DASH M3U8 playback.

Don't talk about live streams. That's not what I mean.

An M3U8 is a file with links to other files. Eg:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=400000,RESOLUTION=426x240
240p30/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=700000,RESOLUTION=640x360
360p30/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1250000,RESOLUTION=842x480
480p30/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1280x720
720p30/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,RESOLUTION=1280x720
720p60/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4500000,RESOLUTION=1920x1080
1080p30/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5800000,RESOLUTION=1920x1080
1080p60/manifest.m3u8

Now there are many ways of creating these files. Ignore all methods but the one I am about to outline.

1) Each file gets ran through FFMPEG to create several .ts files at small intervals each (5 seconds per file)
2) These files are uploaded to IPFS
3) An M3U8 generator of sorts (just a simply way to arrange the .ts files into the M3U8) creates the M3U8 from the IPFS directory listing
4) That M3U8 gets uploaded alongside the .ts files
5) Plant that M3U8 into the uploader (this would be one field, so we won't need a separate section for 240, 480 and so on)
6) The player starts asking the gateway for the small pieces

Why?

I'd have to go into a whole conversation about video streaming, containers and encoders. I can, but that is something I would prefer to do in video format if requested.

**Comment by techcoderx** [comment]
Alive Protocol (which is HLS based) integration with the player has already been worked on [here](https://github.com/techcoderx/embed/tree/alive).

**Comment by DevDeckardCain** [comment]
How do I get a link to the M3U8? If its already working I'd like to just be able to force my videos through this system then pin whatever the output is so I can delete the "old style" containers (.mp4, .avi, etc)

**Comment by techcoderx** [comment]
Alive is still under development. In the meantime feel free to check out the documentation at https://aliveprotocol.com.

**Comment by DevDeckardCain** [comment]
"Alive, a multi-chain decentralized live streaming protocol"

I don't mean live streams. This isn't about live streams, this is about performance.

**Comment by techcoderx** [comment]
Alive integration on the embed player can be extended to normal videos as well as the necessary libraries are already being used, the big question would be the JSON metadata spec for those formats.

**Comment by vaultec81** [comment]
I would also like support for HLS and DASH. Preferably HLS for now as that's the most useful to me, but I would like to have DASH at some point.

**Comment by techcoderx** [comment]
HLS playback support [added here](https://github.com/dtube/embed/commit/cf51b085b96f88aaefb4409f4c1fde6b05a13439)
