### ISSUE TITLE
D.tube Inappropriate videos tab problem.

### ISSUE THREAD

**Issue by sdtyldz** [dtube/embed#6]
#### Expected behavior
D.tube Inappropriate videos tab problem.

#### Actual behavior
Once you're in the website, you can click on the "Inappropriate Videos" tab in the settings section next to your profile picture and select "Show". Then we mark a different option from the API section, refresh the page, and the changes are not registered.
However, without touching the Inappropriate Videos section, only the API section is changed and the page is updated to register the change.
In addition, he does not save again simply by changing the inappropriate videos and refreshing the page.

#### How to reproduce
If the problem is likely to be on the Steemit blockchain, the API settings need to be checked.

https://youtu.be/MW9igC06lRA

* Browser: Google Chrome 
* Operating system: Windows 10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@sedatyildiz/d-tube-inappropriate-videos-tab-problem">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by skzap** [comment]
Our player doesn't need any change related to NSFW videos I believe, all this can be controlled from the production app.
