### ISSUE TITLE
Wrong position for the thumbnails in the video player

### ISSUE THREAD

**Issue by TheGoldenPhoenix** [dtube/embed#8]
#### Expected behavior
In the position x=left=0 and x=right=100% the thumbnails should be inside the window of the player.
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516378822/j7zgtf26nulv0wkrliho.png)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516379002/smzycetdaqhrkhmmvllk.png)

#### Actual behavior
There is a problem with the current setting of the position of the thumbnails
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516377319/qh4vjovsbvwshd0zdt3i.png)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516377443/atackwke2wmgyqxsvlto.png)

#### How to reproduce
1- Go to D.tube and choose any video or just click this video link https://d.tube/#!/v/davidpakman/h5azyp4v
2- Now move your mouse cursor to the beginning/end of the video and  see the behavior of the thumbnail.
* Browser: 
Google Chrome Version 63.0.3239.132 (Official Build) (64-bit).
* Operating system:
Windows 10.

<hr>
<h1> <blockquote>𝕨𝕖 𝕘𝕠 𝕤𝕝𝕠𝕨 𝕓𝕦𝕥 𝕨𝕖 𝕘𝕠 𝕗𝕦𝕣𝕥𝕙𝕖𝕣 @thegoldenphoenix</blockquote>
<hr>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thegoldenphoenix/wrong-position-for-the-thumbnails-in-the-video-player">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by skzap** [comment]
fixed since 0.7 ;)

**Comment by TheGoldenPhoenix** [comment]
a lot of things are better now within Dtube ;)
